apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: loki
data:
  loki-config.yaml: |
    auth_enabled: {{ .Values.loki.auth_enabled }}
    server:
      http_listen_port: {{ .Values.service.port }}
    storage_config:
      aws:
        bucketnames: {{ .Values.loki.storage.s3.bucketnames }}
        endpoint: {{ .Values.loki.storage.s3.endpoint }}
        region: {{ .Values.loki.storage.s3.region }}
        s3forcepathstyle: true
    schema_config:
      configs:
        - from: 2020-10-15
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: index_
            period: 24h
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
