apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loki-role
  namespace: loki
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
