apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loki-rolebinding
  namespace: loki
subjects:
  - kind: ServiceAccount
    name: loki
    namespace: loki
roleRef:
  kind: Role
  name: loki-role
  apiGroup: rbac.authorization.k8s.io
