apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.fullname" . }}
spec:
  selector:
    app: loki
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
