image:
  repository: mattermost/mattermost-team-edition
  tag: 10.12.0@sha256:2f00f862f9205d06a871cecc5a7291de880794a953d9aeaec2ce61d4cb80fe37
  imagePullPolicy: IfNotPresent

service:
  type: ClusterIP
  externalPort: 8065
  internalPort: 8065
  annotations: {}
  # loadBalancerIP:
  loadBalancerSourceRanges: []
