
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.name  }}
  labels:
    app: {{ .Values.deployment.labels  }}
rules:
  {{- if .Values.rbac.rules }}
  {{- toYaml .Values.rbac.rules | nindent 2 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.binding.name  }}
  labels:
    app: {{ .Values.deployment.labels  }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:{{ .Values.rbac.name  }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name  }}
    namespace: {{ .Release.Namespace }}
{{- end }}