# secrets.yaml
{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.database.name }}
  labels:
    app: {{ .Values.deployment.labels }}
type: Opaque
data:
  username: {{ .Values.database.user | b64enc | quote }}
  password: {{ .Values.database.password | b64enc | quote }}
---
{{- end }}

{{- if and .Values.ldap.enabled (not .Values.ldap.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.ldap.name }}
  labels:
   app: {{ .Values.deployment.labels }}
type: Opaque
data:
  bind_dn: {{ .Values.ldap.bind.dn | b64enc | quote }}
  bind_password: {{ .Values.ldap.bind.password | b64enc | quote }}
---
{{- end }}

{{- if not .Values.app.existingSmtpSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.smtp.name }}
  labels:
    app: {{ .Values.deployment.labels }}
type: Opaque
data:
  username: {{ .Values.app.smtpUsername | default "" | b64enc | quote }}
  password: {{ .Values.app.smtpPassword | default "" | b64enc | quote }}
---
{{- end }}

{{- if not .Values.encryption.gpg.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.gpg.name }}
  labels:
    app: {{ .Values.deployment.labels }}
type: Opaque
data:
  # These would need to be populated via --set-file or directly by user
  serverkey.asc: ""
  serverkey_private.asc: ""
---
{{- end }}

{{- if not .Values.encryption.jwt.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.jwt.name }}
  labels:
    app: {{ .Values.deployment.labels }}
type: Opaque
data:
  # This would need to be populated via --set-file or directly by user
  jwt.key: ""
{{- end }}