apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-chart.fullname" . }}-config
data:
{{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
