apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/instance: kyverno
  name: kyverno
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "services", "deployments"]
    verbs: ["get", "list", "create", "update", "delete"]
  # Add more rules as needed
---
