{{- $global := .Values.global }}
{{- if and (kindIs "map" $global) (hasKey $global "serviceAccount") (hasKey $global.serviceAccount "name") (hasKey $global "namespace") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.serviceAccount.name }}
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: kyverno
  apiGroup: rbac.authorization.k8s.io
{{- end }}
