{{- $global := .Values.global }}
{{- if and (kindIs "map" $global) (hasKey $global "namespace") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyverno
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/instance: kyverno
spec:
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kyverno
      app.kubernetes.io/instance: kyverno
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kyverno
        app.kubernetes.io/instance: kyverno
    spec:
      serviceAccountName: {{ .Values.global.serviceAccount.name }}
      containers:
        - name: kyverno
          image: {{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          resources:
            requests:
              memory: {{ .Values.global.resources.requests.memory }}
              cpu: {{ .Values.global.resources.requests.cpu }}
            limits:
              memory: {{ .Values.global.resources.limits.memory }}
              cpu: {{ .Values.global.resources.limits.cpu }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 8000
              name: metrics
{{- end }}
