{{- $metrics := .Values.metrics }}
{{- if and (kindIs "map" $metrics) (hasKey $metrics "enabled") (eq $metrics.enabled true) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kyverno
  namespace: monitoring
  labels:
    {{- if and (hasKey .Values.global "prometheus") (hasKey .Values.global.prometheus "releaseLabel") }}
    release: {{ .Values.global.prometheus.releaseLabel }}
    {{- else }}
    release: prometheus
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kyverno
      app.kubernetes.io/instance: kyverno
  endpoints:
    - port: metrics
      interval: 30s
{{- end }}
