{{- $admission := .Values.admissionController }}
{{- if and (kindIs "map" $admission) (hasKey $admission "rbac") (kindIs "map" $admission.rbac) (hasKey $admission.rbac "create") (eq $admission.rbac.create true) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  {{- if and (.Values.webhooksCleanup.autoDeleteWebhooks) (hasKey .Values.webhooksCleanup.autoDeleteWebhooks "enabled") (eq .Values.webhooksCleanup.autoDeleteWebhooks.enabled true) }}
  finalizers:
    - kyverno.io/webhooks
    - kyverno.io/exceptionwebhooks
    - kyverno.io/globalcontextwebhooks
  {{- end }}
  labels:
    app: kyverno  # Replaced missing include with direct reference
  {{- with $admission.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
