{{- $global := .Values.global }}
{{- if and (kindIs "map" $global) (hasKey $global "namespace") }}
apiVersion: v1
kind: Service
metadata:
  name: kyverno
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/instance: kyverno
spec:
  ports:
    - port: 8000
      targetPort: metrics
      name: metrics
  selector:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/instance: kyverno
{{- end }}
