apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "forgejo.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "forgejo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "forgejo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "forgejo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: forgejo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
            - name: ssh
              containerPort: 22
          env:
            - name: FORGEJO__server__PROTOCOL
              value: "http"
            - name: FORGEJO__server__DOMAIN
              value: {{ .Values.forgejoConfig.hostname | quote }}
            - name: FORGEJO__server__ROOT_URL
              value: {{ .Values.forgejoConfig.rootUrl | quote }}
            - name: FORGEJO__server__SSH_DOMAIN
              value: {{ .Values.forgejoConfig.ssh.domain | quote }}
            - name: FORGEJO__server__SSH_PORT
              value: {{ .Values.forgejoConfig.ssh.port | quote }}
          volumeMounts:
            - name: forgejo-data
              mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: forgejo-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "forgejo.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}