apiVersion: v1
kind: Service
metadata:
  name: {{ include "forgejo.fullname" . }}-web
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "forgejo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceWeb.type }}
  ports:
    - port: {{ .Values.serviceWeb.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "forgejo.selectorLabels" . | nindent 4 }}