apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alertmanager-rules
  namespace: alertmanager           
  labels:
    release: prometheus
spec:
  groups:
    - name: alertmanager.rules
      rules:
        - alert: AlertmanagerDown
          expr: up{job="alertmanager"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Alertmanager instance is down"
            description: "No Alertmanager pods have been running for more than 1 minute."



