{{- /*
  HorizontalPodAutoscaler placeholder.  The prom-stack chart does not deploy
  its own workloads, so autoscaling is not applicable by default.  To enable
  autoscaling for additional components you may add your own configuration
  here and set appropriate values in values.yaml.
*/ -}}

{{- if false }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "prom-stack.fullname" . }}
  labels:
    {{- include "prom-stack.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "prom-stack.fullname" . }}
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
{{- end }}