apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resources
spec:
  validationFailureAction: {{ .Values.requireResources.validationFailureAction | quote }}
  rules:
    - name: validate-resources
      match:
        resources:
          kinds:
            - Pod
      validate:
        {{- with index .Values.requireResources.rules 0 }}
        message: {{ .validate.message | quote }}
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    memory: "?*"
                    cpu: "?*"
                  limits:
                    memory: "?*"
                    cpu: "?*"
        {{- end }}
