replicaCount: 2

image:
  repository: grafana/grafana
  tag: "10.2.0"
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 2Gi
  storageClassName: standard
  mountPath: /var/lib/grafana/dashboards

admin:
  existingSecret: grafana-admin-secret

database:
  type: mysql
  host: your-mysql-host:3306
  name: grafana
  user: grafanauser
  password:
    existingSecret: grafana-mysql-secret
    key: mysql-password

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - grafana.192.168.49.2.nip.io
  tls:
    - hosts:
        - grafana.192.168.49.2.nip.io
      secretName: grafana-tls

grafana.ini:
  server:
    root_url: https://grafana.192.168.49.2.nip.io
  auth.anonymous:
    enabled: false
  metrics:
    enabled: true
  analytics:
    reporting_enabled: false
  security:
    disable_gravatar: true
    cookie_secure: true
    allow_embedding: false

securityContext:
  runAsUser: 472
  fsGroup: 472

rbac:
  create: true

serviceAccount:
  create: true
  name: grafana-sa

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local:80
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy
      - name: Alertmanager
        type: alertmanager
        url: http://alertmanager.monitoring.svc.cluster.local:9093
        access: proxy

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
