{{- if .Values.auditLogging.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-secrets-audit-logging
  namespace: {{ .Release.Namespace }}
data:
  audit-logging.yaml: |
    apiVersion: audit.k8s.io/v1
    kind: Policy
    metadata:
      name: external-secrets-audit-policy
    rules:
      - level: {{ .Values.auditLogging.level | default "Metadata" }}
    {{- if .Values.auditLogging.includeSecrets }}
      - resources:
          - group: ""
            resources: ["secrets"]
        level: RequestResponse
    {{- end }}
{{- end }}

