replicaCount: 3

image:
  repository: 597088047986.dkr.ecr.us-east-1.amazonaws.com/connect-backend
  tag: "8742"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ecr-pull-secret

secret:
  name: connect-backend

serviceAccount:
  create: true
  name: backend-serviceaccount

service:
  type: NodePort
  port: 80
  nodeport: 30800

readinessProbe:
  httpGet:
    path: /healthz
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /healthz
    port: 80
  initialDelaySeconds: 20
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3

securityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  allowPrivilegeEscalation: false

resources:
  limits:
    cpu: 700m
    memory: 512Mi
  requests:
    cpu: 350m
    memory: 256Mi

networkPolicy:
  enabled: true
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}

configMap:
  enabled: true
  name: connect-backend

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: true
  minAvailable: 2

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: backend.prod.webforxtech.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: prod-tls-secret
      hosts:
        - backend.prod.webforxtech.com
