replicaCount: 2

image:
  repository: 597088047986.dkr.ecr.us-east-1.amazonaws.com/connect-backend
  tag: "8742"
  pullPolicy: Always

imagePullSecrets:
  - name: ecr-pull-secret

secret:
  name: connect-backend

serviceAccount:
  create: true
  name: backend-serviceaccount

service:
  type: ClusterIP
  port: 80

readinessProbe:
  httpGet:
    path: /healthz
    port: 80
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /healthz
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3

securityContext:
  enabled: false
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
  allowPrivilegeEscalation: false

networkPolicy:
  enabled: false
  ingress: []
  egress: []

configMap:
  name: connect-backend

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

pdb:
  enabled: false

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: backend.dev.webforxtech.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
