replicaCount: 1

loki:
  auth_enabled: false
  storage:
    type: s3
    s3:
      bucketnames: "YOUR_S3_BUCKET"
      endpoint: s3.amazonaws.com
      region: "AWS_REGION"
      existingSecret: loki-s3-secret
