apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "cadvisor.fullname" . }}
  labels:
    {{- include "cadvisor.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "cadvisor.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cadvisor.name" . }}
      annotations:
        {{- toYaml .Values.prometheus.annotations | nindent 8 }}
    spec:
      serviceAccountName: cadvisor-sa
      containers:
        - name: cadvisor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: docker
              mountPath: /var/lib/docker
              readOnly: true
      volumes:
        - name: rootfs
          hostPath:
            path: /
        - name: var-run
          hostPath:
            path: /var/run
        - name: sys
          hostPath:
            path: /sys
        - name: docker
          hostPath:
            path: /var/lib/docker
