apiVersion: v1
kind: ServiceAccount
metadata:
  name: cadvisor-sa
  namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cadvisor-role
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cadvisor-rolebinding
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: cadvisor-sa
    namespace: monitoring
roleRef:
  kind: Role
  name: cadvisor-role
  apiGroup: rbac.authorization.k8s.io

