replicaCount: 2

image:
  repository: quay.io/prometheus/alertmanager
  tag: v0.26.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9093

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: alertmanager.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  enabled: false
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClass: "STORAGECLASS"

mattermostWebhookUrl:   "MMWEBHOOK_UR"

secrets:
  mattermostWebhookUrl: "MMWEBHOOK_UR"

serviceAccount:
  create: true
  name: ""

podDisruptionBudget:
  enabled: true
  minAvailable: 1
