apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secretstore
  namespace: external-secrets
spec:
  provider:
    vault:
      server: https://vault.edusuc.net
      path: Dev-secret
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token

