# Core Linkerd Control Plane Settings
global:
  namespace: linkerd
  identityTrustAnchorsPEM: ""
  linkerdVersion: stable-2.14.3
  clusterDomain: cluster.local

identity:
  issuer:
    scheme: linkerd.io/tls
    clockSkewAllowance: 20s
    issuanceLifetime: 24h0m0s
    crtExpiry: ""
    tls:
      crtPEM: ""
      keyPEM: ""

proxy:
  logLevel: info
  resources:
    cpu:
      request: 100m
      limit: 500m
    memory:
      request: 50Mi
      limit: 250Mi

controllerReplicas: 3
heartbeatSchedule: "0 */1 * * *"

proxyInjector:
  enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi

highAvailability:
  enabled: true

viz:
  enabled: true
  prometheus:
    enabled: true
    retention: "6h"
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  grafana:
    enabled: true
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

jaeger:
  enabled: true
  collector:
    enabled: true
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  ui:
    enabled: true
